* Watch Me Build a Modern Webapp

** It will be a network of AI Cameras!

*** Cameras are less than $50
*** Start with 1 camera

** Hardware Independence

*** Raspberry PI + CSI Camera
*** Jetson NVidia Nano + CSI Camera
*** Ubuntu + USB Camera
*** MacPro + Builtin Camera

** Features

*** Controled I/O

**** RESTFul API
**** MQTT messaging control

*** A/I Mods

We support the OpenCV computer vision algorithm and a multitude of A/I
a modes that can be chained together and dynamically applied and
unapplied to live stream(s).

Roll your own A/I and plug it in!

**** Real Time A/I

Real Time A/I algorithms process video stream inline and must produce
results fast enough to feed them back into the control systmes
decision algorithm.

**** Deep Learning

RedEye comes with an archive module that is used by the Deep Learning
module for post stream processing and learning.

Deep learning producing intelligence models that become ever smarter
the longer they are able to participate in the learning process. We
will build this portion out largely in the cloud.

*** Modern Reactive Front End                                         :vuejs:

Run the application from any display connected to the internet! It was
written in modern front-end / back-end client server style code.

*** The Backend Is BadAss!

A master piece of microservices strictly adhereing to modern day
_DevOps_ best practices.

** Are you Interested in This Project?

- Programmer looking to step up their game?
- Business owner or Project Manner needing a webapp
- DeVops person with some cutting edge advice?

> Please join this list, I would love to hear your questions. And even
  get advice if you have been down this road before!

** Need to Have Software Built

*** Discuss Transparent Project Planning 

We do my form of _Transparent Project Planning_ such that
**everybody** is on the same page once development begins.


