#+title: The Software Development Process
#+subtitle: Take control of your project
#+date: 2020-04-05
#+draft: true

* Making Software Predictable

Are you are involved in a software development project that is
spinning out of control? Or maybe you want to keep from losing control?

If so, I created a cool little /Software Project Starter Kit/ you may
find helpful (and calming!). This guide is not about /programming/
rather is is all about the /process/ of **delivering** /production/
software. 

** The Process will Set You Free

I have worked on over a hundred software projects, a few great
successes, some honorable mentions, and a couple miserable failures. 

It has been my observation that successful projects tend to all have
/just the right process/ in place. The projects that failed did so for
a variety of reasons, which often included no process to too much
process. 

#+BEGIN_QUOTE:
No process leads to chaos, bugs and arguments. Too much process kills efficiency,
creativity and morale.
#+END_QUOTE:

I am on a mission to define /Just Enough Process/ to keep projects
organized, predictable, efficient and a pleasure to work on. To that
end I have put together a 6-part series that will help take the
mystery and stress out of /managing software development/.

** Software Starter Kit

In this series I establish 6 critical resources that should be part of
any non-trivial tutorial style alwayswe will use to
build a work-flow from 100% free tools (like github) and Open Source
software.  All project demos documentation and code can be found in
github for free!

*** What to Expect

We will cover the entire Software Development Life Cycle (SDLC)
process before any code is written, through the delivery and
maintenance of a production piece of software. 

**** Table of Contents

+ Clearly stated goals and Milestones
+ Version Control all the Things
+ Test First and Always
+ Automatic Updates
+ Issue Tracking
+ Analytics and Elastic

** Join Me!

Want to come along, learn and maybe even pitch in?

