#+title: Predictable Software Development
#+description: Do you ever stress over a software project, or lose sleep wondering how to start?
#+subtitle: Take control of your project
#+date: 2020-04-05

Are you are involved in a software development project that is
spinning out of control? Or maybe you want to keep from losing control?

If so, I created a cool little /Software Project Starter Kit/ you may
find helpful (and calming!). This guide is not about /programming/
rather is is all about the /process/ of **delivering** /production/
software. 

** The Process will Set You Free

I have worked on over a hundred software projects, a few great
successes, some honorable mentions, and a couple miserable failures. 

It has been my observation that successful projects tend to all have
/just the right process/ in place. The projects that failed did so for
a variety of reasons, which often included no process to too much
process. 

#+BEGIN_QUOTE:
No process leads to chaos, bugs and arguments. Too much process kills efficiency,
creativity and morale.
#+END_QUOTE:

I am on a mission to define /Just Enough Process/ to keep projects
organized, predictable, efficient and a pleasure to work on. To that
end I have put together a 6-part series that /I believe/ are the
**mandatory** foundations of beginning the journey to peaceful
software releases.

*** Why I am doing this?

I am a Software Engineer and I love what I do, it is also what I do
for a living. 

The people that I work for, my clients, customers, employers and users
all deserve the absolute best from my knowledge and experience as well
as my present day skills.

#+BEGIN_QUOTE:
I want to provide the best possible service for my clients, and
free my team to focus on their strengths by establishing /Just Enough Process/.
#+END_QUOTE:

I am hell bent on understanding and providing my clients /predictable/
software projects delivered on time and in budget. It makes my life
soooo much easier, and it's great for business. But most important, it
is the best thing for my clients!  



** The Software Project Starter Kit

In this series I establish 6 critical resources that should be part of
any non-trivial tutorial style alwayswe will use to
build a work-flow from 100% free tools (like github) and Open Source
software.  All project demos documentation and code can be found in
github for free!
