#+title: No Hassle Updates with CI/CD
#+date: 2020-04-03
#+weight: 40

Glad to hear testing is going well!

Now it is time to Get the soccer out to the users For the real
test. This test is measurable Buyer customers feedback 

** Good Software is Continually Improved

The greater the success software Is directly proportionate to The
number of features that are requested As well as the number of bugs
that are found. 

> Bug reports means your softwar is getting used.!.

That is obvious if people are happy using a software That they might
have some requests that would flow in from time to time. 

What might seem counterintuitive is the fact that, Even well done
successful software will have bugs. Period. Good teams understand and
embrace that... The Bugs will be fixed And the customers will be even
happier 

On the other hand, Bad software that is really buggy We'll never
really get used (the day of Micro$oft FUD are happy fading in the
past). 

** Customer Expect Seamless Updates 

Rolling out new versions of software to your users in a manner that
does not make their life a nightmare should be your primary goal!

Customers do not want forklift style updates to their
software. Certainly the days of having to backup all your dataMaybe
even back up your entire computer hard drive, Uninstall a previous
version of the software Hold your breath, Type in A 64 character
nonsensical string of gibberish, Click start, Listen to the CD start
the world. 

Hold your breath, And watch a number of minutes of a progress bar is
tick by.

And if all a successful you smileLittle little bit of breath out,
Opened version of the software hope everything is okay. Going to the
file menu to open up your backed up data, 

Hold your breath again, Click load And hope to high heaven and it read
your old data correctly.

If So all is well carry-on.

If not, Call customer support, Prepare to wait for Possibly hours, Oh
and by the way Have your credit card ready to go, Just in case.

Support ain't free..

** Nope, that ain't good no more..

Now on the other hand logging to want to Google's things And look
aroundNo doubt some things of changed on you.  Okay baby they went a
little overboard, We need to find somewhere and write the middle. 

